name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/test.yml"
      - "tests/**"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/test.yml"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies with uv
        run: uv sync --all-groups

      - name: Run tests with uv
        run: uv run pytest tests/
